# -*- coding: utf-8 -*-
import io

path = "index.html"
with io.open(path, "r", encoding="utf-8") as f:
    src = f.read()

old_notes = '''        data_center_notes: "UPGRADED 2026-08-04 (overnight follow-up): Board adopted a 'High Resource Demand Facilities and Data Center' ordinance (Chapter 36, new Sec. 36-151) on May 26, 2026 — preemptive, no developer proposal on file. Origin was a GRASSROOTS resident draft (Jonathan Greenberg/Rob Pattinson, Feb 2026) that explicitly required review by 'the Township Attorney and Carlisle Wortman Associates' before formal consideration. STRONG NEW EVIDENCE: a May 5, 2026 CWA memo (Megan Masson-Minock/Brady Heath) to neighboring Dexter Township, transmitting a full HRDF draft explicitly copied from Pittsfield Township ('modified for Dexter Township'), contains a Purpose paragraph and HRDF/data-center definitions that are VERBATIM IDENTICAL to the purpose language news coverage quotes from Scio's own adopted ordinance ('balance local economic benefits with protection of public health, safety, welfare, natural resources, and neighborhood character'). This is the clearest documented instance of CWA's template propagating in real time, caught in writing, the same month as Scio's adoption — strong circumstantial evidence CWA substituted its own template for the residents' draft (whose numbers — PUE 1.4, WUE 1.8 L/kWh, 55/45 dBA, mandatory Community Benefit Agreement — do NOT match). Supervisor Jillian Kerry confirmed the board was 'advised not to include specific details regarding community benefits at this time' — the CBA was dropped on advice of counsel/consultant. Full literal Sec. 36-151 text (numeric standards: materials %, PUE, dBA, setbacks) STILL not obtained — Municode/Granicus/municipalcodeonline.com all block automated access; a direct records request to the Clerk is the recommended next step. See PACT-Vault Documents/CWA-Ordinance-Pattern-Comparison.",'''

new_notes = '''        data_center_notes: "RESOLVED 2026-08-04 (afternoon): full primary-source drafting history obtained from PC/BOT packets Mo downloaded directly. CONFIRMED (not circumstantial): CWA planner Laura Kreps introduced a full 'Section 36-151 Data Centers' draft Dec 1, 2025/Jan 12, 2026, with PC minutes stating outright it was 'similar to the ordinance being considered by Pittsfield Township' -- the Pittsfield-template match is in Scio's own meeting minutes. That original CWA draft used a flat 65 dBA noise standard (no day/night split). A competing 'Data Center Overlay District v2.0' draft surfaced Feb 2026 (16 sections incl. mandatory Community Benefit Agreement, 55/45 dBA day/night noise standard) -- the same one requiring 'Township Attorney and Carlisle Wortman Associates' review. March 24, 2026: PC directed CWA to reconcile the two drafts under the broader 'High Resource Demand Facilities' framing. April 13, 2026 public hearing (7-0 recommend-to-Board vote): the ADOPTED noise standard is 55 dBA day / 45 dBA night -- the STRICTER, resident-aligned figure won over CWA's original 65 dBA -- plus a new 65 dB(C) low-frequency cap and a 100% renewable-process-energy requirement. Resident Rob Pattinson pushed for mandatory on-site generation (50%+); declined. No mandatory CBA survived (zero mentions in the hearing's own minutes), matching Supervisor Kerry's public statement it was dropped on consultant/counsel advice. Board adopted May 26, 2026. Net finding: CWA held the pen and structure throughout (confirmed Pittsfield lineage), but the final numeric standards are a genuine hybrid incorporating the stricter resident-proposed noise limits -- not a one-sided template override. Only remaining gap: a single clean copy of the final signed text. Full timeline: PACT-Vault Documents/CWA-Ordinance-Pattern-Comparison.",'''

assert old_notes in src, "old Scio notes block not found"
assert src.count(old_notes) == 1, "not unique"
src = src.replace(old_notes, new_notes)

with io.open(path, "w", encoding="utf-8") as f:
    f.write(src)

print("patched OK, new size", len(src))
